apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbs-simulator
  labels:
    app: cbs-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbs-simulator
  template:
    metadata:
      labels:
        app: cbs-simulator
    spec:
      containers:
      - name: cbs-simulator
        image: ${DOCKER_REGISTRY}/cbs-simulator:latest # L'image sera construite et poussée par Jenkins
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-simulator-service
spec:
  selector:
    app: cbs-simulator
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP # Ou LoadBalancer si vous voulez l'exposer à l'extérieur du cluster

