---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  namespace: cbs-system
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: ammariamine/middleware:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: CBS_SIMULATOR_URL
          value: "http://cbs-simulator-service:4000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Middleware Service (ClusterIP for internal communication)
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
  namespace: cbs-system
spec:
  type: ClusterIP
  selector:
    app: middleware
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
# Middleware NodePort Service (for external access)
apiVersion: v1
kind: Service
metadata:
  name: middleware-nodeport
  namespace: cbs-system
spec:
  type: NodePort
  selector:
    app: middleware
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
